services:
  app-prod:
    image: fadyamir/app-prod
    container_name: app-prod # compose
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      network: host
      secrets:
        - SECRET_ENVS
    # ports:
    #   - 3000:3000
    volumes:
      - ./apps/web/uploads:/app/apps/web/uploads
    env_file:
      - ./envs/production/.env.production.docker
      - ./envs/production/.env.production.docker.local
    networks:
      - proxy
      - internal-db
    depends_on:
      - db-prod
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=Host(`el-bagoushi.com`) || Host(`www.el-bagoushi.com`)'
      - 'traefik.http.routers.frontend.tls=true'
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 80s

  db-prod:
    image: postgres:16.4-alpine
    container_name: db-prod # compose
    ports:
      - 5432:5432
    user: '${MY_UID}:${MY_GID}'
    volumes:
      - db-prod-data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/data-prod
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    networks:
      - internal-db
    deploy:
      restart_policy:
        condition: on-failure

  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Africa/Cairo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/ssl/:/ssl-certs/
      - ./data/logs:/logs:rw

volumes:
  db-prod-data:

networks:
  internal-db:
    external: false
  proxy:
    external: true

secrets:
  SECRET_ENVS:
    file: .env.production.build.local
  postgres_user:
    file: secrets/production/postgres-user.txt
  postgres_password:
    file: secrets/production/postgres-password.txt
  postgres_db:
    file: secrets/production/postgres-db.txt
