packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  zod: ^3.23.8
  ky: ^1.5.0
  next-auth: 5.0.0-beta.20
  prettier: ^3.3.3
  eslint: ^9.7.0
  typescript: ^5.5.3
  tsc-files: ^1.1.4

catalogs:
  react18:
    react: 18.2.0
    react-dom: 18.2.0
    '@types/react': ~18.2.79
    '@types/react-dom': ^18.3.0
