global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
    http:
      tls:
        certResolver: default

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
  # file:
  #   filename: /config.yml
  #   watch: true

certificatesResolvers:
  default:
    acme:
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      email: fady2jericho@gmail.com
      storage: /ssl-certs/acme.json
      httpChallenge:
        entryPoint: http

accessLog:
  filePath: '/logs/access.log'
  fields:
    headers:
      names:
        User-Agent: keep

log:
  filePath: '/logs/traefik.log'
  level: INFO
